updated parallellshell due to a weird problem https://github.com/darkguy2008/parallelshell/issues/57
-------------------
> meter@1.0.0 start /Users/kniberg/Documents/Henrik/sveasmart/meter
> parallelshell 'node src/start.js' 'node src/start_pulse_detector.js'

child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at exports.spawn (child_process.js:493:38)
    at /Users/kniberg/Documents/Henrik/sveasmart/meter/node_modules/parallelshell/index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/kniberg/Documents/Henrik/sveasmart/meter/node_modules/parallelshell/index.js:100:6)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)